### ISSUE TITLE
white color background

### ISSUE THREAD

**Issue by Christain** [bacy/titlebar#1]
如果我的TitleBar的背景色设置成白色，而手机状态栏字体颜色是白色的，这样就看不出来了。有没有方法再设置成白色背景的时候，状态栏字体变成其他系统颜色。谢谢

**Comment by bacy** [comment]
如果是小米的系统是可以修改状态栏颜色的，去他们开发网站，有相关说明。但是一般的android系统，并不支持状态栏文字换色，这种情况就不要使用沉浸式了。

**Comment by Christain** [comment]
我知道状态栏文字的颜色是不能改的，现在最新版QQ和一些其他应用，TitleBar都是白色的，但状态栏的颜色系统会默认变成黑色。目前还没有找到是用的什么方法。

**Comment by bacy** [comment]
状态栏颜色改变只可能定制化过的系统或者使用了xposed这样的框架
