### ISSUE TITLE
横屏之后，出问题了

### ISSUE THREAD

**Issue by wenkchan** [bacy/titlebar#3]
标题没居中，右边布局的也没有到右边。。间距跟竖屏的时候一样

**Comment by bacy** [comment]
![qq 20160520150448](https://cloud.githubusercontent.com/assets/5163569/15419954/4ef7c89e-1e9c-11e6-969a-59b0cca8e01c.png)
没出现你说的情况

**Comment by cc5416** [comment]
亲，gradle依赖的名字是什么啊，搜不到啊

**Comment by wenkchan** [comment]
竖屏转到横屏之后会出问题，一开始是横屏的话是正常

**Comment by wenkchan** [comment]
找到原因了，原因是重写了onLayout方法，然后我那个screenWidth还是竖屏的值，重新获取然后重新requestlayout重新onlayout就好，忘了一个。。。这个Activity我是没有重建的。。
