### ISSUE TITLE
修改图片大小

### ISSUE THREAD

**Issue by l16426434** [bacy/titlebar#4]
可以修改 左右两边的imageview 大小吗？

**Comment by bacy** [comment]
这个本身不想弄太复杂，所以没有暴露很多ui细节修改的api出来，imgageview的高是match的，宽度是wrap的，如果你觉得太拥挤了，可以自己修改mActionPadding和mOutPadding这两个值。outpadding是外圈间距，actionpadding是图标之间的间距
