### ISSUE TITLE
Fragment使用的异常

### ISSUE THREAD

**Issue by xusheng927** [bacy/titlebar#6]
内容直接跑到系统的状态栏里面去了。
Activity是好的。Fragment不兼容吗？

**Comment by xusheng927** [comment]
![360 1212_17_34_01](https://cloud.githubusercontent.com/assets/8056822/21094579/8c523a24-c092-11e6-82db-5fdc853db3e6.png)

**Comment by bacy** [comment]
mTitleBar.setImmersive(true)
我不确定你代码中怎么加入的，不过如果你的app中使用了沉浸的话，把这个设置为true

**Comment by xusheng927** [comment]
现在才有空处理这个bug。Mark一下：
出现这样的原因是，布局文件里引用的TitleBar，必须在根布局下，不能放在子布局里，否则就会图中这样失效。

**Comment by xusheng927** [comment]
还有一点要注意，Fragment里使用必须在onCreateView的生命周期之前设置
