### ISSUE TITLE
横屏宽度自适应的问题

### ISSUE THREAD

**Issue by tooodooo** [bacy/titlebar#7]
例子中是自适应了，但我用的单个Activity，子页面用的Fragment

而且设置了屏幕方向变化不调用 onCreate 方法

横屏的时候宽度没有自适应。自己加的控件没问题。
![1](https://cloud.githubusercontent.com/assets/6067607/21427641/b77e0592-c890-11e6-9a3c-bdda945652b5.jpg)
![2](https://cloud.githubusercontent.com/assets/6067607/21427640/b77ad4d0-c890-11e6-961a-e22d7706f172.jpg)

**Comment by bacy** [comment]
Titlebar的宽度，不要去屏幕宽度，取onMeasure中算出来的宽度即可
