### ISSUE TITLE
使用Edit时标题文字会消失

### ISSUE THREAD

**Issue by iamZ2z** [bacy/titlebar#8]
使用了titlebar做标题栏后很方便，但是随之也带来了问题，在使用EditText时，中间标题栏文字会消失，请问是什么原因

**Comment by bacy** [comment]
你好，请问是调用了setCustomTitle方法在Title中间添加了EditText吗？如果想要中间Title文字再出来，需要再调用一次setCustomTitle(null)

**Comment by iamZ2z** [comment]
抱歉这么久才回。不是这样，是在标题栏下面有个edittext(不属于标题栏)，当进入页面时自动弹出输入法，然后title就消失了，移开edittext的焦点又恢复。

**Comment by bacy** [comment]
这个你得设置activity的windowsoftinput为adjustresize

**Comment by iamZ2z** [comment]
明白谢谢，还有请问右面的Text怎么设置字体颜色和大小呢

**Comment by iamZ2z** [comment]
明白，谢谢
